### ISSUE TITLE
Access AWS MSK

### ISSUE THREAD

**Issue by yurir** [VerizonAdPlatforms/bandar-log#28]
We are trying to add bandarlog for MSK and facing issues. On first run we got 
```
ERROR connectors.KafkaConnector: Cannot obtain leaders offsets for topic:[Set(input_test)], cause java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.CoordinatorNotAvailableException: The coordinator is not available.
```
After restarting bandarlog we started to get 
```
ERROR connectors.KafkaConnector: Cannot obtain leaders offsets for topic:[Set(input_test)], cause java.util.concurrent.TimeoutException: Futures timed out after [1 second]
```

MSK security group has an open port for bandarlog machine. Any tips in debugging would be helpful.

Thanks

**Comment by alexey-kotlyar** [comment]
is the zookeeper accessible for the machine hosting the bandarlog docker container? also, what are the open ports for the MSK security group and how did you verify their availability?
i think you should try running describe-cluster first and make sure it's running as expected, e.g.
`aws kafka describe-cluster --region us-east-1 --cluster-arn "ClusterArn"`

**Comment by alexey-kotlyar** [comment]
in theory, after that describe command you will see the zookeeper connect string and can investigate further, trying to connect to this cluster via any other kafka cli tool, e.g. describe topics in the living cluster if you already created those

**Comment by yurir** [comment]
@alexey-kotlyar thanks for quick reply. we added brokers list to bandarlog configuration and now the error gone, but we getting zero values for in, out and lag.

**Comment by alexey-kotlyar** [comment]
@yurir is this issue still actual or we can close it for good?

**Comment by yurir** [comment]
works properly for MSK now. closing it.
